### ISSUE TITLE
Jumping to closing/opening paranthese not working in vim-mode

### ISSUE THREAD

**Issue by saemideluxe** [foxoman/zed-nim#6] opened 2024-08-20 04:57 UTC
Hi

First of all, thanks for making this Zed extension available, it is highly appreciated.

I just noticed that using `%` to jump between parantheses/brackets/braces does not work in Zed when editing a *.nim file. Other languages work. Also `vi(` and friends work. I was wondering whether this can be fixed and if I am reporting this at the right place. I imagine this could also originate from tree-sitter-nim.

**Comment by zai1208** [comment] 2024-08-28 04:31
I helped contribute to this project so I believe I would be of help, I believe the issue is in the config.toml file. Could you please give an example of which language this works for so I could create a pull request to add a fix?

**Comment by saemideluxe** [comment] 2024-08-28 05:06
That would be great!
So, with Python it works in zed as it works in vim/neovim. Including `( [ { ) ] }` (e.g. typing `vi]` would select the inner content of the current brackets). Is that enough information?

**Comment by zai1208** [comment] 2024-08-28 05:19
I think adding brackets.scm, should solve the issue (this is copied from the Python extension btw)

**Comment by zai1208** [comment] 2024-08-28 05:24
If you quickly need it, you can just download my fork of the repo add it into the extension folder (unzipped) (I can’t recall where it is) then zed will automatically pick it up.

**Comment by zai1208** [comment] 2024-08-28 08:40
Did it work so I can close this issue?

**Comment by zai1208** [comment] 2024-09-02 21:59
@saemideluxe does it work?

**Comment by saemideluxe** [comment] 2024-09-03 02:49
I tried you repo, but when I try to install it as a Zed-Dev-Extension it looks like nothing happens. When I copy the `*.scm` files into the existing extension directory, the Nim extension no longer seems to work (not even syntax highlighting coming up.

But don't worry too much, I am not using Zed+Nim on a regular basis (yet), just thought I report it here.

**Comment by foxoman** [comment] 2024-09-03 06:44
Thank you for reporting,

@zai1208 let me test your pull request later in the day, thank you very much.

**Closed** 2024-09-03 18:41 UTC
